apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-080237
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-ogp-images-for-sharing-bfba
    path: k8s/manifests-080237
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
