apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-6f0223
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: delete-unused
    path: k8s/manifests-6f0223
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
