apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-bd2e6e
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-api-plan-from-markdown-b8de
    path: k8s/manifests-bd2e6e
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
