apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-dee09a
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: fix-map
    path: k8s/manifests-dee09a
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
