apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-adff64
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-mobile-ui-improvement-plan-20d1
    path: k8s/manifests-adff64
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
