apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-651659
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-loading-ui-according-to-plan-6bbe
    path: k8s/manifests-651659
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
