version: '3.8'

services:
  # Next.js Development Server
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: journee-dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Use anonymous volume for node_modules to prevent overwriting
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    env_file:
      - .env.local
    stdin_open: true
    tty: true
    networks:
      - journee-network

networks:
  journee-network:
    driver: bridge
