apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-1d75e6
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: fix-map-bug
    path: k8s/manifests-1d75e6
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
