apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-098f6b
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: test
    path: k8s/manifests-098f6b
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
