apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-ae405a
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: delete-auto-progress
    path: k8s/manifests-ae405a
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
