apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-multi-deploy
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: manifests-multi-deploy
    path: k8s/manifests-multi-deploy
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
