apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-d2df70
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-shift-enter-for-newlines-4ac3
    path: k8s/manifests-d2df70
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
