apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-d1142c
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/add-login-button-and-restrict-comments-6e40
    path: k8s/manifests-d1142c
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
