apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-4494ee
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/proceed-with-implementation-after-plan-revision-1746
    path: k8s/manifests-4494ee
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
