apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-642ab9
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: last-cursor
    path: k8s/manifests-642ab9
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
