apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-d02bc6
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/respond-to-plan-revision-and-start-implementation-0f33
    path: k8s/manifests-d02bc6
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
