apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-9f5889
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-gemini-2-5-flash-from-plan-e725
    path: k8s/manifests-9f5889
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
