/**
 * Phase 5.1 新機能確認用のモックデータ
 * 
 * このファイルには、以下の新機能を確認するためのサンプルデータが含まれています：
 * - 画像URL付きスポット
 * - 位置情報（緯度経度）付きスポット → MapView表示
 * - 各種カテゴリのスポット
 * - テンプレート設定
 */

import { ItineraryData } from '@/types/itinerary';

export const sampleKyotoItinerary: ItineraryData = {
  id: 'sample-kyoto-001',
  title: '京都 2泊3日の旅',
  destination: '京都',
  startDate: '2025-11-15',
  endDate: '2025-11-17',
  duration: 3,
  summary: '古都京都の魅力を満喫する2泊3日の旅。清水寺、金閣寺、伏見稲荷大社などの定番スポットを巡りながら、京料理も楽しめます。',
  schedule: [
    {
      day: 1,
      date: '2025-11-15',
      title: '東山エリア散策',
      totalDistance: 8.5,
      totalCost: 5500,
      spots: [
        {
          id: 'spot-001',
          name: '京都駅',
          description: '旅のスタート地点。新幹線で到着後、まずは京都駅周辺を散策。',
          category: 'transportation',
          scheduledTime: '10:00',
          duration: 30,
          location: {
            lat: 34.9858,
            lng: 135.7584,
            address: '京都府京都市下京区東塩小路町',
          },
          estimatedCost: 0,
          notes: '新幹線の到着時刻により調整可能',
        },
        {
          id: 'spot-002',
          name: '清水寺',
          description: '京都を代表する寺院。清水の舞台から京都市街を一望できます。紅葉の季節は特に美しい。',
          category: 'sightseeing',
          scheduledTime: '11:00',
          duration: 90,
          location: {
            lat: 34.9949,
            lng: 135.7850,
            address: '京都府京都市東山区清水1-294',
          },
          estimatedCost: 400,
          imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
          notes: '拝観料400円。混雑する午後は避けるのがおすすめ。',
        },
        {
          id: 'spot-003',
          name: '二年坂・三年坂',
          description: '清水寺へ続く石畳の坂道。京都らしい風情ある街並みが楽しめます。',
          category: 'sightseeing',
          scheduledTime: '13:00',
          duration: 60,
          location: {
            lat: 34.9962,
            lng: 135.7810,
            address: '京都府京都市東山区桝屋町',
          },
          estimatedCost: 0,
          imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800',
          notes: '食べ歩きや土産物店が多い。写真スポットも豊富。',
        },
        {
          id: 'spot-004',
          name: '祇園 おくむら',
          description: '京料理の老舗。季節の食材を使った会席料理が楽しめます。',
          category: 'dining',
          scheduledTime: '14:30',
          duration: 90,
          location: {
            lat: 35.0037,
            lng: 135.7745,
            address: '京都府京都市東山区祇園町南側',
          },
          estimatedCost: 3500,
          imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
          notes: '予約推奨。ランチコース3,500円〜',
        },
        {
          id: 'spot-005',
          name: '八坂神社',
          description: '祇園祭で有名な神社。夕暮れ時の参拝もおすすめ。',
          category: 'sightseeing',
          scheduledTime: '16:30',
          duration: 45,
          location: {
            lat: 35.0036,
            lng: 135.7785,
            address: '京都府京都市東山区祇園町北側625',
          },
          estimatedCost: 0,
          imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
        },
        {
          id: 'spot-006',
          name: 'ホテル（四条河原町周辺）',
          description: 'チェックイン。市街地中心部のホテルで便利。',
          category: 'accommodation',
          scheduledTime: '18:00',
          duration: 60,
          location: {
            lat: 35.0039,
            lng: 135.7681,
            address: '京都府京都市中京区河原町四条',
          },
          estimatedCost: 8000,
          notes: '1泊8,000円（朝食付き）',
        },
      ],
    },
    {
      day: 2,
      date: '2025-11-16',
      title: '金閣寺と嵐山',
      totalDistance: 15.2,
      totalCost: 6800,
      spots: [
        {
          id: 'spot-007',
          name: '金閣寺',
          description: '金箔で覆われた舎利殿が有名な寺院。紅葉の季節は特に美しい。',
          category: 'sightseeing',
          scheduledTime: '09:00',
          duration: 75,
          location: {
            lat: 35.0394,
            lng: 135.7292,
            address: '京都府京都市北区金閣寺町1',
          },
          estimatedCost: 500,
          imageUrl: 'https://images.unsplash.com/photo-1480796927426-f609979314bd?w=800',
          notes: '拝観料500円。朝早い時間が空いていておすすめ。',
        },
        {
          id: 'spot-008',
          name: '龍安寺',
          description: '石庭で有名な寺院。15個の石の配置が美しい。',
          category: 'sightseeing',
          scheduledTime: '11:00',
          duration: 60,
          location: {
            lat: 35.0345,
            lng: 135.7184,
            address: '京都府京都市右京区龍安寺御陵ノ下町13',
          },
          estimatedCost: 500,
          imageUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800',
        },
        {
          id: 'spot-009',
          name: '嵐山 竹林の小径',
          description: '竹林に囲まれた幻想的な小径。SNS映えスポットとしても人気。',
          category: 'sightseeing',
          scheduledTime: '13:00',
          duration: 45,
          location: {
            lat: 35.0174,
            lng: 135.6723,
            address: '京都府京都市右京区嵯峨小倉山田淵山町',
          },
          estimatedCost: 0,
          imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800',
          notes: '早朝や夕方は比較的空いています',
        },
        {
          id: 'spot-010',
          name: '嵐山 湯豆腐 嵯峨野',
          description: '嵐山名物の湯豆腐。新鮮な豆腐と京野菜が楽しめます。',
          category: 'dining',
          scheduledTime: '14:00',
          duration: 75,
          location: {
            lat: 35.0156,
            lng: 135.6741,
            address: '京都府京都市右京区嵯峨天龍寺芒ノ馬場町',
          },
          estimatedCost: 2800,
          imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
          notes: '湯豆腐御膳2,800円。紅葉シーズンは予約推奨。',
        },
        {
          id: 'spot-011',
          name: '渡月橋',
          description: '嵐山のシンボル的な橋。桂川にかかる美しい橋から眺める景色は絶景。',
          category: 'sightseeing',
          scheduledTime: '16:00',
          duration: 30,
          location: {
            lat: 35.0134,
            lng: 135.6770,
            address: '京都府京都市右京区嵯峨中ノ島町',
          },
          estimatedCost: 0,
          imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
        },
        {
          id: 'spot-012',
          name: '京都駅周辺（夕食）',
          description: 'ホテルに戻る途中、京都駅周辺で夕食。',
          category: 'dining',
          scheduledTime: '18:30',
          duration: 60,
          location: {
            lat: 34.9858,
            lng: 135.7584,
            address: '京都府京都市下京区東塩小路町',
          },
          estimatedCost: 3000,
          notes: 'ラーメン小路や伊勢丹のレストラン街がおすすめ',
        },
      ],
    },
    {
      day: 3,
      date: '2025-11-17',
      title: '伏見稲荷大社と帰路',
      totalDistance: 6.3,
      totalCost: 2500,
      spots: [
        {
          id: 'spot-013',
          name: 'ホテル チェックアウト',
          description: 'ホテルをチェックアウト。荷物は京都駅のロッカーへ。',
          category: 'accommodation',
          scheduledTime: '09:00',
          duration: 30,
          location: {
            lat: 35.0039,
            lng: 135.7681,
            address: '京都府京都市中京区河原町四条',
          },
          estimatedCost: 0,
        },
        {
          id: 'spot-014',
          name: '伏見稲荷大社',
          description: '千本鳥居で有名な神社。朱色の鳥居が連なる景色は圧巻。',
          category: 'sightseeing',
          scheduledTime: '10:00',
          duration: 120,
          location: {
            lat: 34.9671,
            lng: 135.7727,
            address: '京都府京都市伏見区深草藪之内町68',
          },
          estimatedCost: 0,
          imageUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=800',
          notes: '頂上まで登ると往復2-3時間。無料で参拝可能。',
        },
        {
          id: 'spot-015',
          name: '稲荷 いなり寿司専門店',
          description: '伏見稲荷名物のいなり寿司。参拝の後にぴったり。',
          category: 'dining',
          scheduledTime: '12:30',
          duration: 45,
          location: {
            lat: 34.9676,
            lng: 135.7720,
            address: '京都府京都市伏見区深草一ノ坪町',
          },
          estimatedCost: 1200,
          imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
          notes: 'いなり寿司セット1,200円',
        },
        {
          id: 'spot-016',
          name: '京都駅（お土産購入）',
          description: '京都駅でお土産を購入。八つ橋、抹茶スイーツなど。',
          category: 'other',
          scheduledTime: '14:00',
          duration: 60,
          location: {
            lat: 34.9858,
            lng: 135.7584,
            address: '京都府京都市下京区東塩小路町',
          },
          estimatedCost: 3000,
          notes: '伊勢丹や駅ビルのお土産店が充実',
        },
        {
          id: 'spot-017',
          name: '京都駅 出発',
          description: '新幹線で帰路へ。お疲れ様でした！',
          category: 'transportation',
          scheduledTime: '16:00',
          duration: 30,
          location: {
            lat: 34.9858,
            lng: 135.7584,
            address: '京都府京都市下京区東塩小路町',
          },
          estimatedCost: 0,
          notes: '新幹線の時刻により調整',
        },
      ],
    },
  ],
  totalBudget: 45000,
  status: 'completed',
  createdAt: new Date('2025-10-07T10:00:00'),
  updatedAt: new Date('2025-10-07T14:30:00'),
  isPublic: false,
  template: 'standard',
};

export const sampleTokyoItinerary: ItineraryData = {
  id: 'sample-tokyo-001',
  title: '東京グルメ旅 2日間',
  destination: '東京',
  startDate: '2025-12-01',
  endDate: '2025-12-02',
  duration: 2,
  summary: '東京の美食を堪能する2日間。築地、銀座、渋谷のグルメスポットを巡ります。',
  schedule: [
    {
      day: 1,
      date: '2025-12-01',
      title: '築地・銀座グルメ',
      totalDistance: 5.2,
      totalCost: 12000,
      spots: [
        {
          id: 'spot-101',
          name: '築地場外市場',
          description: '新鮮な海鮮と築地グルメを楽しめる市場。',
          category: 'dining',
          scheduledTime: '08:00',
          duration: 120,
          location: {
            lat: 35.6654,
            lng: 139.7707,
            address: '東京都中央区築地4丁目',
          },
          estimatedCost: 3000,
          imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
          notes: '海鮮丼、玉子焼き、寿司などを食べ歩き',
        },
        {
          id: 'spot-102',
          name: '銀座 ショッピング',
          description: '銀座の高級ブランド店やデパートを散策。',
          category: 'other',
          scheduledTime: '11:00',
          duration: 90,
          location: {
            lat: 35.6717,
            lng: 139.7649,
            address: '東京都中央区銀座4丁目',
          },
          estimatedCost: 0,
        },
        {
          id: 'spot-103',
          name: '銀座 すきやばし次郎',
          description: 'ミシュラン三つ星の寿司店。（架空の予約）',
          category: 'dining',
          scheduledTime: '13:00',
          duration: 90,
          location: {
            lat: 35.6709,
            lng: 139.7638,
            address: '東京都中央区銀座4-2-15',
          },
          estimatedCost: 50000,
          imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
          notes: '※これはサンプルデータです',
        },
      ],
    },
    {
      day: 2,
      date: '2025-12-02',
      title: '渋谷・原宿',
      totalDistance: 4.8,
      totalCost: 8000,
      spots: [
        {
          id: 'spot-104',
          name: '明治神宮',
          description: '都会のオアシス。静かな雰囲気で参拝できます。',
          category: 'sightseeing',
          scheduledTime: '09:00',
          duration: 60,
          location: {
            lat: 35.6764,
            lng: 139.6993,
            address: '東京都渋谷区代々木神園町1-1',
          },
          estimatedCost: 0,
          imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
        },
        {
          id: 'spot-105',
          name: '原宿 竹下通り',
          description: '若者文化の発信地。クレープやカラフルなスイーツが人気。',
          category: 'other',
          scheduledTime: '10:30',
          duration: 90,
          location: {
            lat: 35.6702,
            lng: 139.7027,
            address: '東京都渋谷区神宮前1丁目',
          },
          estimatedCost: 1500,
          imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800',
        },
      ],
    },
  ],
  totalBudget: 75000,
  status: 'draft',
  createdAt: new Date('2025-10-07T11:00:00'),
  updatedAt: new Date('2025-10-07T11:30:00'),
  template: 'foodie',
};

/**
 * モックデータをZustandストアに読み込むヘルパー関数
 */
export const loadSampleItinerary = (type: 'kyoto' | 'tokyo' = 'kyoto') => {
  return type === 'kyoto' ? sampleKyotoItinerary : sampleTokyoItinerary;
};