apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-e42ac1
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/investigate-and-fix-comment-feature-bug-222f
    path: k8s/manifests-e42ac1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
