apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-9086c2
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: fix-map-api
    path: k8s/manifests-9086c2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
