apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-aaf1a7
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-based-on-plan-f924
    path: k8s/manifests-aaf1a7
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
