apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-fdf2e5
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-revised-save-status-plan-60c6
    path: k8s/manifests-fdf2e5
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
