apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-c0aec4
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: delete-phase
    path: k8s/manifests-c0aec4
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
