apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-d9a8c8
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: refactor-phase-10
    path: k8s/manifests-d9a8c8
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
