apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-f2d6f1
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-my-page-api-integration-1e4b
    path: k8s/manifests-f2d6f1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
