apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-5ed57e
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/create-implementation-plan-for-removing-unauthenticated-handling-754f
    path: k8s/manifests-5ed57e
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
