apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-e8f8e7
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/write-blog-post-with-issue-details-3ee7
    path: k8s/manifests-e8f8e7
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
