apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-573443
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/integrate-bookmark-saving-to-database-186b
    path: k8s/manifests-573443
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
