apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-2d544c
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/refactor-itinerary-with-checkpoints-6a6f
    path: k8s/manifests-2d544c
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
