apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-4a3279
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/line-bot-d99d
    path: k8s/manifests-4a3279
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
