apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-9f2197
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: refacotr
    path: k8s/manifests-9f2197
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
