apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-9d8ae9
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: codex/fix-issue-#72-igid7j
    path: k8s/manifests-9d8ae9
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
