apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-5f79a7
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/merge-main-update-plan-and-implement-7609
    path: k8s/manifests-5f79a7
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
