apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-8bb1dd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/change-journee-icon-823f
    path: k8s/manifests-8bb1dd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
