apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-aa2a66
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/improve-docker-build-process-ef2e
    path: k8s/manifests-aa2a66
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
