apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-351df8
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: delete-ui-for-mobile
    path: k8s/manifests-351df8
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
