apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-5113b0
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/preserve-message-drafts-during-editing-8a9a
    path: k8s/manifests-5113b0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
