apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-3df777
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/analyze-and-fix-logout-bug-a1f7
    path: k8s/manifests-3df777
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
