apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-4fbfaa
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-plan-to-remove-unauthenticated-handling-4a8e
    path: k8s/manifests-4fbfaa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
