apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-9fd2c9
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/confirm-plan-and-implement-spot-numbers-0de1
    path: k8s/manifests-9fd2c9
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
