apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-12117d
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: codex/fix-issue-#72-y85k1w
    path: k8s/manifests-12117d
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
