apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-9d892a
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-additional-features-based-on-updated-plan-ee69
    path: k8s/manifests-9d892a
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
