apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-26c145
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: fix-login-bug
    path: k8s/manifests-26c145
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
