apiVersion: apps/v1
kind: Deployment
metadata:
  name: journee-auth-prod
  namespace: journee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: journee-auth-prod
  template:
    metadata:
      labels:
        app: journee-auth-prod
    spec:
      imagePullSecrets:
      - name: gcr-pull-secret
      containers:
      - name: journee-auth
        image: gcr.io/my-docker-471807/journee:v2.7.1
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/secret/key.json
        - name: NEXTAUTH_URL
          value: https://auth.aooba.net
        # 認証プロキシモード: 認証サービスなのでfalse
        - name: AUTH_PROXY_MODE
          value: "false"
        - name: AUTH_SERVICE_URL
          value: https://auth.aooba.net
        # Cookie共有ドメイン
        - name: COOKIE_DOMAIN
          value: .aooba.net
        # Secretから環境変数を注入
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: journee-env
              key: GEMINI_API_KEY
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: journee-env
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: journee-env
              key: GOOGLE_CLIENT_SECRET
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: journee-env
              key: NEXTAUTH_SECRET
        - name: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: journee-env
              key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: journee-env
              key: NEXT_PUBLIC_SUPABASE_URL
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: journee-env
              key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: journee-env
              key: SUPABASE_SERVICE_ROLE_KEY
        - name: NEXT_PUBLIC_BASE_URL
          value: https://auth.aooba.net
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: journee-env
              key: GITHUB_TOKEN
        - name: GITHUB_OWNER
          value: AobaIwaki123
        - name: GITHUB_REPO
          value: journee
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: journee-auth-prod
  namespace: journee
spec:
  selector:
    app: journee-auth-prod
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: journee-auth-prod-ingress
  namespace: journee
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: "cloudflare-tunnel"
  rules:
  - host: auth.aooba.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: journee-auth-prod
            port:
              number: 80
