apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-8c4b4f
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: refine-build-process
    path: k8s/manifests-8c4b4f
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
