apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-256830
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-plan-to-remove-vercel-references-e671
    path: k8s/manifests-256830
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
