apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-cdc97d
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/create-implementation-plan-and-pr-bac0
    path: k8s/manifests-cdc97d
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
