apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-9cf2ff
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/create-implementation-plan-and-pull-request-4fad
    path: k8s/manifests-9cf2ff
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
