apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-b30a02
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-requested-feature-from-pr-088f
    path: k8s/manifests-b30a02
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
