apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-17e697
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-plan-to-remove-unauthenticated-handling-3bf1
    path: k8s/manifests-17e697
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
