apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-ace31b
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/implement-option-a-for-streaming-animation-7a02
    path: k8s/manifests-ace31b
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
