apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journee-967efc
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/journee'
    targetRevision: cursor/show-branch-mode-indicator-after-login-a9b6
    path: k8s/manifests-967efc
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: journee
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
